permalinks:
  page: /:slug/
siteConfig:
  title: RPG Bros
  url: https://rpg-bros.netlify.com/
  author: ""
  description: A document for my group's collaborative RPG
  date: "2019-2020"
themeConfig:
  nav:
    - text: Home
      link: /
    - text: Resources
      link: /resources/
    - text: Campaign
      link: /game/
markdown:
  plugins:
    - resolve: markdown-it-attrs
