permalinks:
  page: /:slug/
siteConfig:
  title: RPG Bros
  url: https://rpg-bros.netlify.com/
  author: ""
  description: A document for my group's collaborative RPG
  date: "2019"
themeConfig:
  nav:
    - text: Home
      link: /
    - text: Games
      link: /games/
    - text: Resources
      link: /resources/
markdown:
  plugins:
    - resolve: markdown-it-attrs
