permalinks:
  page: /:slug/
siteConfig:
  title: RPG Bros
  url: https://rpg-bros.netlify.com/
  author: Rin and friends
  description: A document for my group's collaborative RPG
themeConfig:
  nav:
    - text: Home
      link: /
    - text: Game
      link: /game/
    - text: Resources
      link: /resources/
markdown:
  plugins:
    - resolve: markdown-it-attrs
