backend:
  name: github
  branch: master
  repo: rinto357/rpg-bros
  open_authoring: true

media_folder: static/uploads
publish_mode: editorial_workflow

collections:
  - name: "simple" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Show Header (default true)", name: "header", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}